// Fixture copy and labels are separate from UI markup; no data comes from a workspace.
export const labels = {
  devices: 'Dispositivos',
  profileName: 'Nome do perfil',
  newProfile: 'Novo perfil',
  workspace: 'Workspace',
  branch: 'Branch',
  context: 'Contexto',
  sandbox: 'Sandbox',
  attentionTitle: 'Uma decisão antes de continuar',
  reviewChanges: 'Revisar alterações',
  once: 'Permitir uma vez',
  task: 'Permitir neste trabalho',
  always: 'Permitir sempre neste caminho',
  deny: 'Negar',
  risk: 'Risco',
  reason: 'Motivo',
  scope: 'Escopo',
  protected: 'Proteções mantidas',
  provider: 'Provider',
  model: 'Modelo',
  variant: 'Variante',
  profile: 'Perfil',
  customProfiles: 'Editar perfis',
  saveDefault: 'Salvar como padrão deste perfil',
  edit: 'Editar',
  remove: 'Remover',
  up: 'Mover para cima',
  down: 'Mover para baixo',
  add: 'Adicionar',
  reset: 'Reiniciar cenário',
  queued: 'Na fila',
  processed: 'Processando',
  nothingQueued: 'Nada na fila. A próxima mensagem mantém a seleção do envio.',
  pending: 'Intervenção pendente',
  safeStep: 'Aplicar na etapa segura',
  openSession: 'Abrir sessão',
  newSession: 'Nova sessão',
  backSessions: 'Voltar às sessões',
  summary: 'Resumo',
  files: 'Arquivos',
  previous: 'Anterior',
  next: 'Próximo',
  checkpoint: 'Restaurar checkpoint',
  originalChanges: 'Alterações anteriores preservadas',
  fullOutput: 'Ver saída completa',
  evidence: 'Evidências simuladas',
  notValidated: 'Não validado',
  noExecution: 'Nenhum comando será executado. Nenhum arquivo será lido ou alterado.',
  noProvider: 'Nenhum provider será contatado. Modelos e cotas são fixtures.',
  confirmation: 'Confirmação simulada',
  providerTitle: 'Compartilhar contexto com outro provider?',
  providerBody:
    'Mensagens, plano, trechos de código e resultados relevantes poderão compor o contexto do novo provider. Não inclui outras sessões, o repositório inteiro ou valores secretos.',
  rememberProvider: 'Não perguntar novamente para este provider nesta sessão',
  confirm: 'Confirmar no protótipo',
  connect: 'Simular conexão',
  reconnect: 'Simular snapshot atualizado',
  quotaChoice: 'Retomar quando a cota voltar',
  quotaWaiting: 'Aguardando renovação informada · 18:40 (mock)',
  noFallback: 'Sem fallback pago automático',
  selectRequired: 'Escolha explícita necessária',
  useWorktree: 'Usar worktree',
  shareDirectory: 'Compartilhar este diretório',
  localUse: 'Autorizar inspeção protegida',
  trustWorkspace: 'Confiar neste workspace',
  allowNoSandbox: 'Trabalhar sem sandbox',
  restored: 'Checkpoint simulado restaurado. Suas mudanças não foram descartadas.',
  manage: 'Gerenciar',
  healthy: 'Saudável',
  degraded: 'Degradado',
  disabled: 'Desativado',
  pinned: 'Pinned · usuário',
  onDemand: 'Sob demanda · projeto',
  restart: 'Reiniciar',
  enable: 'Ativar',
  disable: 'Desativar',
  inspect: 'Inspecionar',
  import: 'Importar configuração',
  importBody:
    'Prévia do import: adicionar playwright no projeto. Nenhuma credencial será copiada; nenhuma tool é autorizada automaticamente.',
  permission: 'Permissões',
  deleteMemory: 'Excluir memória: perguntar',
  readMemory: 'Ler memória: permitir',
  writeMemory: 'Gravar no projeto: autorizado',
  newTools: 'Tools novas ou acesso ampliado exigem nova aprovação.',
  permanent: 'Permanente neste caminho',
  revoke: 'Revogar',
  pair: 'Parear dispositivo',
  pairTitle: 'Pareamento ilustrativo',
  pairBody: 'Código e QR são ilustrativos, não credenciais. Nenhuma conexão será estabelecida.',
  deviceCode: 'Código mock: CARA-2048',
  permissionsMobile: 'Ver sessões, enviar prompts, parar/intervir e approvals comuns.',
  adminDisabled:
    'Políticas globais, acessos permanentes e ausência de sandbox desativados por padrão.',
  deviceAdded: 'Celular de revisão adicionado ao cenário, sem conexão real.',
  cpu: 'Paralelismo',
  memory: 'Memória',
  disk: 'Armazenamento',
  limits: 'Limites',
  processes: 'Processos supervisionados',
  keepRunning: 'Manter rodando',
  clean: 'Limpar cache descartável',
  cleanBody:
    'Prévia: 640 MiB de cache descartável. Sessões, checkpoints, diffs e evidências não serão apagados.',
  budgets:
    'Sem capacidade para subagents? Continuar sozinho. Nunca aumentar limites automaticamente.',
  secretRule: 'Segredos nunca vão para o modelo, chat ou logs. Uso local não autoriza exposição.',
  sudoRule: 'Elevação de privilégios bloqueada, inclusive em Yolo.',
  globalProvider: 'Desativar avisos de troca de provider em todas as sessões',
  sessionScope: 'Só nesta sessão',
  projectScope: 'Neste projeto',
  userScope: 'Padrão do usuário',
  language: 'Idioma',
  englishPartial: 'Inglês parcial · demonstração da estrutura de tradução',
  savedMock: 'Preferência salva apenas no estado do protótipo.',
  defaultsMock: 'Padrão do perfil atualizado no protótipo; novas sessões reais ainda não existem.',
  effective: 'Configuração efetiva',
  source: 'Origem',
  explain: 'Explicar precedência',
  noSecretConfig: 'Credenciais não ficam no TOML. Projeto não pode ampliar permissões.',
  doctorIntro: 'Diagnóstico simulado. Nenhuma inspeção da máquina foi executada.',
  report: 'Prévia de relatório sanitizado',
  fix: 'Simular correção segura',
  reportBody:
    'Sem tokens, prompts, conteúdo de código, valores de env ou caminho completo do usuário.',
  steps: 'Etapas',
  changed: 'O que mudou',
  completedTitle: 'Trabalho validado',
  changesSummary: '4 arquivos · +124 −38',
  conversationTitle: 'Corrigir rotação de refresh tokens',
  scopePath: '~/Code/quintal-api',
  activeSession: 'Sessão ativa encontrada',
  activeBody:
    'Corrigir login · Auto · aberta há 12 minutos. Não criaremos uma sessão duplicada silenciosamente.',
  attach: 'Anexar à sessão',
  startSeparate: 'Simular nova sessão',
  emptyTitle: 'Seu próximo trabalho começa aqui',
  emptyBody: 'Abra um workspace e escolha um perfil. O protótipo não acessa seus arquivos.',
  openMock: 'Abrir workspace simulado',
  keyboard: 'Atalhos',
  keyboardBody:
    'Ctrl/Cmd+K abre ações; Alt+P ou Shift+Tab no composer alterna perfil; Ctrl/Cmd+Enter envia; Esc fecha detalhes.',
};

export const demo = {
  user: 'Corrige a rotação dos refresh tokens e adiciona testes de reutilização. Preserva minhas alterações no middleware.',
  response:
    'A rotação agora invalida o token anterior na mesma transação. Adicionei cobertura de reutilização e preservei suas mudanças no middleware. A publicação da branch ainda depende da sua autorização.',
  tools: [
    {
      name: 'Inspecionar fluxo de autenticação',
      detail: '6 arquivos relevantes · leitura protegida',
      status: 'done',
    },
    {
      name: 'Atualizar auth/service.rs',
      detail: 'Escrita atômica · alterações anteriores preservadas',
      status: 'done',
    },
    { name: 'cargo test --workspace', detail: '183 passaram · 0 falharam · 4,8 s', status: 'done' },
  ],
  plan: [
    'Inspecionar implementação',
    'Reproduzir reutilização do token',
    'Corrigir rotação na transação',
    'Adicionar testes de integração',
    'Validar e revisar alterações',
  ],
  files: [
    { path: 'auth/service.rs', plus: 48, minus: 12, previous: false },
    { path: 'auth/repository.rs', plus: 21, minus: 4, previous: false },
    { path: 'auth/service_test.rs', plus: 55, minus: 22, previous: false },
    { path: 'auth/middleware.rs', plus: 0, minus: 0, previous: true },
  ],
  diff: [
    '  pub async fn rotate_token(&self, token: Token) {',
    '-     self.tokens.insert(token).await?;',
    '+     let mut tx = self.db.begin().await?;',
    '+     self.tokens.invalidate_previous(&mut tx).await?;',
    '+     self.tokens.insert(&mut tx, token).await?;',
    '+     tx.commit().await?;',
    '  }',
  ],
  output:
    'Mock output\n$ cargo test --workspace\nrunning 183 tests\ntest refresh_token_rotation ... ok\ntest refresh_token_reuse_detection ... ok\n183 passed; 0 failed; finished in 4.8s\n\nNenhum comando foi executado.',
  validations: ['cargo fmt --check', 'cargo clippy', 'cargo test --workspace', 'API smoke test'],
  approval: {
    command: 'git push origin feature/refresh-token',
    remote: 'github.com/acme/quintal-api',
    branch: 'feature/refresh-token',
    risk: 'Escrita em repositório remoto',
    reason: 'Publicar a branch para abrir a PR solicitada.',
  },
  sessions: [
    {
      id: 'quintal',
      name: 'quintal-api',
      title: 'Corrigir rotação de tokens',
      status: 'Approval pendente',
      time: 'agora',
      attention: true,
    },
    {
      id: 'tixnow',
      name: 'tixnow-web',
      title: 'Retry no checkout',
      status: 'Rodando testes',
      time: '7 min',
      attention: false,
    },
    {
      id: 'carapana',
      name: 'carapana',
      title: 'Revisar atalhos da TUI',
      status: 'Em pausa',
      time: '18 min',
      attention: false,
    },
  ],
  mcp: [
    { name: 'ai-memory', scope: 'pinned', state: 'healthy' },
    { name: 'playwright', scope: 'on-demand', state: 'disabled' },
    { name: 'postgres', scope: 'project', state: 'healthy' },
  ],
  skills: [
    'security',
    'maintainability',
    'testing',
    'local-development',
    'frontend-design',
    'git',
    'rust',
  ],
  doctor: [
    'Core',
    'Config',
    'Storage',
    'Git',
    'Sandbox',
    'Provider auth',
    'Models',
    'Skills',
    'MCP',
    'Resource limits',
    'Child processes',
    'Remote configuration',
  ],
};
