// UI text registry. English can be completed without changing components.
export const pt = {
  sessions: 'Sessões',
  hideSidebar: 'Esconder barra lateral',
  showSidebar: 'Mostrar barra lateral',
  updates: 'Atualizações',
  attention: 'Precisa de você',
  running: 'Em andamento',
  recent: 'Recentes',
  conversation: 'Conversa',
  activity: 'Atividade',
  plan: 'Plano',
  changes: 'Alterações',
  validation: 'Validação',
  mcp: 'MCP',
  skills: 'Skills',
  providers: 'Providers',
  devices: 'Dispositivos',
  resources: 'Recursos',
  settings: 'Configurações',
  doctor: 'Diagnóstico',
  config: 'Configuração efetiva',
  prototype: 'Protótipo · dados simulados',
  executing: 'Executando',
  next: 'Próxima mensagem',
  queue: 'Fila',
  send: 'Enviar para a fila',
  intervene: 'Intervir agora',
  pause: 'Pausar',
  stop: 'Parar',
  resume: 'Retomar',
  scenario: 'Cenário de revisão',
  theme: 'Tema',
  light: 'Claro',
  dark: 'Escuro',
  system: 'Sistema',
  command: 'Buscar ação ou sessão',
  close: 'Fechar',
  save: 'Salvar',
  cancel: 'Cancelar',
  simulateStep: 'Simular próxima etapa segura',
  simulateFinish: 'Simular conclusão',
  offline: 'Desconectado. Ações bloqueadas; seu rascunho está preservado.',
  placeholder: 'O que vamos fazer a seguir?',
  review: 'Revisão do Delivery 0',
};
export type CopyKey = keyof typeof pt;
export const english: Partial<Record<CopyKey, string>> = {
  sessions: 'Sessions',
  hideSidebar: 'Hide sidebar',
  showSidebar: 'Show sidebar',
  updates: 'Updates',
  attention: 'Needs attention',
  running: 'Running',
  recent: 'Recent',
  conversation: 'Conversation',
  activity: 'Activity',
  plan: 'Plan',
  changes: 'Changes',
  validation: 'Validation',
  devices: 'Devices',
  resources: 'Resources',
  settings: 'Settings',
  doctor: 'Doctor',
  executing: 'Executing',
  next: 'Next message',
  queue: 'Queue',
  send: 'Queue message',
  intervene: 'Intervene now',
  pause: 'Pause',
  stop: 'Stop',
  resume: 'Resume',
  prototype: 'Prototype · simulated data',
  close: 'Close',
  save: 'Save',
  cancel: 'Cancel',
};
export function translate(key: CopyKey, locale: 'pt-BR' | 'en') {
  return locale === 'en' ? (english[key] ?? pt[key]) : pt[key];
}
